INSERT INTO buisness VALUES (1,'Rhynoodle','In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',1),
	(2,'Mudo','Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',2),
	(3,'Yombu','Phasellus in felis. Donec semper sapien a libero. Nam dui.',3),
	(4,'Oodoo','Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',4),
	(5,'Wikivu','Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',5),
	(6,'Yodoo','Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',6),
	(7,'Layo','Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',7),
	(8,'Izio','Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',8),
	(9,'Thoughtworks','Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',9),
	(10,'Dynabox','Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',10),
	(11,'Tazz','In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',11),
	(12,'Midel','Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',12),
	(13,'Photospace','Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',13),
	(14,'Voomm','Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',14),
	(15,'Quinu','Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',15),
	(16,'Wordtune','Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',16),
	(17,'Flipopia','Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',17),
	(18,'Divanoodle','Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',18),
	(19,'Feedfire','Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',19),
	(20,'Fivespan','In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',20),
	(21,'Gabtype','In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',21),
	(22,'Ailane','Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',22),
	(23,'Mybuzz','Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',23),
	(24,'Wordtune','Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',24),
	(25,'Blogpad','Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',25),
	(26,'Mydeo','Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',26),
	(27,'Kazio','Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',27),
	(28,'DabZ','Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',28),
	(29,'Flipopia','Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',29),
	(30,'Kazio','Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',30),
	(31,'Tambee','Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',31),
	(32,'Wikizz','Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',32),
	(33,'Shuffletag','Sed ante. Vivamus tortor. Duis mattis egestas metus.',33),
	(34,'Youopia','Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',34),
	(35,'InnoZ','In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',35),
	(36,'Topiczoom','Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',36),
	(37,'Dynabox','Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',37),
	(38,'Muxo','Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',38),
	(39,'Zoombeat','Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',39),
	(40,'Browsebug','Phasellus in felis. Donec semper sapien a libero. Nam dui.',40),
	(41,'Browsezoom','Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',41),
	(42,'Vidoo','Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',42),
	(43,'Trudoo','Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',43),
	(44,'Pixope','Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',44),
	(45,'Skyndu','In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',45),
	(46,'Plambee','In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',46),
	(47,'Riffpath','Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',47),
	(48,'Ooba','Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',48),
	(49,'Meezzy','In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',49),
	(50,'InnoZ','Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',50);
