insert into company (user_id, name, description) values (8, 'Yozio', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into company (user_id, name, description) values (19, 'Riffwire', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.');
insert into company (user_id, name, description) values (14, 'Zoonder', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into company (user_id, name, description) values (24, 'Yodoo', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into company (user_id, name, description) values (1, 'Buzzshare', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into company (user_id, name, description) values (7, 'Oyoloo', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into company (user_id, name, description) values (7, 'Brainsphere', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into company (user_id, name, description) values (19, 'Edgepulse', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into company (user_id, name, description) values (9, 'Trunyx', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.');
insert into company (user_id, name, description) values (1, 'Geba', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into company (user_id, name, description) values (1, 'Agivu', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into company (user_id, name, description) values (21, 'Voomm', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into company (user_id, name, description) values (5, 'Fanoodle', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into company (user_id, name, description) values (2, 'Zoovu', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into company (user_id, name, description) values (8, 'Leenti', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.');
insert into company (user_id, name, description) values (26, 'Trunyx', 'Fusce consequat. Nulla nisl. Nunc nisl.');
insert into company (user_id, name, description) values (7, 'Blognation', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into company (user_id, name, description) values (8, 'Tagchat', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into company (user_id, name, description) values (14, 'Buzzshare', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into company (user_id, name, description) values (8, 'Meedoo', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into company (user_id, name, description) values (10, 'Quatz', 'Fusce consequat. Nulla nisl. Nunc nisl.');
insert into company (user_id, name, description) values (20, 'Twimm', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into company (user_id, name, description) values (21, 'Skajo', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into company (user_id, name, description) values (12, 'Eire', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into company (user_id, name, description) values (17, 'Voonix', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.');