INSERT INTO jobOffer (company_id, title, description, city) VALUES 
(1, 'Développeur web', 'Développement de sites internet pour des clients variés', 'Paris'),
(1, 'Designer web', 'Création de maquettes pour des sites internet', 'Paris'),
(1, 'Chef de projet web', 'Gestion de projets de développement web', 'Paris'),
(3, 'Chargé de marketing digital', 'Création de campagnes publicitaires en ligne', 'Lyon'),
(3, 'Community manager', 'Gestion des réseaux sociaux de l''entreprise', 'Lyon'),
(3, 'Chargé de communication', 'Création de contenu pour les réseaux sociaux', 'Lyon'),
(5, 'Analyste de données', 'Analyse de données pour des clients variés', 'Marseille'),
(5, 'Développeur backend', 'Développement de solutions backend pour des clients variés', 'Marseille'),
(5, 'Développeur frontend', 'Développement de solutions frontend pour des clients variés', 'Marseille'),
(7, 'Support client', 'Gestion des demandes des clients', 'Toulouse'),
(7, 'Chargé de relation client', 'Gestion de la relation client', 'Toulouse'),
(7, 'Chargé de support technique', 'Gestion des demandes techniques des clients', 'Toulouse'),
(9, 'Gestionnaire de produit', 'Gestion de produits pour des clients variés', 'Bordeaux'),
(9, 'Chef de produit', 'Gestion de produits pour des clients variés', 'Bordeaux'),
(9, 'Responsable produit', 'Gestion de produits pour des clients variés', 'Bordeaux');